---

# NOTE: It is possible to install latest version of pip tool with the get-pip.py script:
# https://pip.pypa.io/en/stable/installing/
- name: Install latest pip version with 'get-pip' script
  shell: "curl -sSL https://bootstrap.pypa.io/get-pip.py | python"
  become: yes
  tags:
    - docker-install-dockerpy
    - docker-install-compose

# NOTE: In Debian Jessie, pip runs into errors if installed from 'python-pip' package.
# - name: Install pip from the official APT repository
#   apt:
#     name: python-pip
#     update_cache: yes
#   when: ansible_os_family == 'Debian'
#   become: yes
#   tags:
#     - docker-install-dockerpy
#     - docker-install-compose

- name: Install docker-py
  pip:
    name: docker-py
    version: "{{ docker_py_lib_version }}"
  become: yes
  tags:
    - docker-install-dockerpy

# NOTE: It is possible to install 'docker-compose' by getting the official script from
# the github projet by I prefer using pip for that.

- name: Install docker-compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_tool_version }}"
  become: yes
  tags:
    - docker-install-compose
