---

- name: Get current Linux kernel version
  shell: "uname -r | cut -d'-' -f1"
  register: linux_kenel_version
  changed_when: false

- name: Kernel version not supported
  fail:
    msg: "Your kernel must be 3.10 at minimum !"
  when: linux_kenel_version.stdout | version_compare('3.10', '<')

- name: Check whether docker exists
  shell: "command -v docker"
  ignore_errors: True
  register: docker_cmd_exists
  changed_when: false

- debug:
    msg: 'It seems that Docker engine is already installed.'
  when: docker_cmd_exists.rc == 0
